MASTER_WORDS({ id:"tmw-읽기-2", type:"read", label:"TOPIK MASTER 제2회 읽기 so'zlari",
  title:"제2회 읽기", sub:"TOPIK MASTER · 읽기 so'zlari",
  words:[
    ["불편(하다)","noqulay"],["합격하다","imtihondan o'tmoq"],["정책","siyosat"],["달려 있다","bog'liq bo'lmoq"],["정신과","psixiatriya"],["지혜","donolik"],
    ["강사","ustoz, lektor"],["오염되다","ifloslanmoq"],["해산물","dengiz mahsulotlari"],["살리다","qutqarmoq"],["이성적","aqlli, ratsional"],["운세","taqdir folbinligi"],
    ["건축","qurilish, arxitektura"],["박람회","ko'rgazma, yarmarka"],["규모","hajm, miqyos"],["친환경","ekologik toza"],["소득","daromad"],["실태","haqiqiy holat"],
    ["연금","pensiya"],["용돈","cho'ntak puli"],["취직","ishga joylashish"],["인식","qarash, tushuncha"],["퍼지다","yoyilmoq"],["계열","yo'nalish, tarmoq"],
    ["인체","inson tanasi"],["근육","mushak"],["차지하다","egallamoq"],["비중","ulush, salmoq"],["영양소","oziq modda"],["운반","tashish"],
    ["섬유","tola"],["화제","muhokama mavzusi"],["의류","kiyim-kechak"],["통기성","havo o'tkazuvchanlik"],["착용","kiyish, taqish"],["장치","qurilma"],
    ["생활필수품","kundalik zarur buyum"],["열량","kaloriya"],["맥박","tomir urishi"],["휴가를 내다","ta'til olmoq"],["한적하다","sokin, kimsasiz"],["골목길","tor ko'cha"],
    ["고혈압","yuqori qon bosimi"],["질환","kasallik"],["주성분","asosiy tarkib"],["섭취","iste'mol qilish"],["유발하다","qo'zg'atmoq"],["발길","qadam, kelish"],
    ["편견","xurafot, noto'g'ri qarash"],["관람객","tomoshabin"],["결제","to'lov"],["구매(하다)","xarid qilmoq"],["변비","qabziyat"],["발병률","kasallanish darajasi"],
    ["증상","alomat"],["악화(되다)","yomonlashmoq"],["시각적","vizual"],["요소","element, tarkibiy qism"],["각인되다","muhrlanmoq"],["시선을 끌다","diqqatni tortmoq"],
    ["눈치를 보다","kayfiyatini poylamoq"],["수술","operatsiya"],["심상치 않다","g'ayritabiiy"],["고열","yuqori isitma"],["재발(하다)","qaytalanmoq"],["억울하다","nohaqlikdan ranjimoq"],
    ["허탈하다","bo'shashmoq"],["소화기","o't o'chirgich"],["화재","yong'in"],["맞먹다","teng kelmoq"],["통증","og'riq"],["의사소통","muloqot"],
    ["양호하다","qoniqarli, yaxshi"],["위반","qoidabuzarlik"],["단속하다","nazorat qilmoq"],["추월","quvib o'tish"],["철저히","qat'iy, tubdan"],["조상","ajdod"],
    ["신성하다","muqaddas"],["고목","qari daraxt"],["숭배하다","sig'inmoq"],["금기","taqiq, tabu"],["으깨다","maydalamoq"],["소화(시키다)","hazm qilmoq"],
    ["성실함","mehnatkashlik"],["부류","toifa"],["꿀벌","asalari"],["부지런(하다)","tirishqoq"],["곤충","hasharot"],["고령화","aholining qarishi"],
    ["못지않다","qolishmaydi"],["자외선","ultrabinafsha nur"],["저항력","qarshilik kuchi"],["주름","ajin"],["감추다","yashirmoq"],["미생물","mikroorganizm"],
    ["살균법","sterilizatsiya usuli"],["유통 기간","saqlash muddati"],["사이비","soxta, yolg'on"],["혈액형","qon guruhi"],["상관관계","o'zaro bog'liqlik"],["기질","fe'l-atvor"],
    ["무시되다","e'tiborsiz qolmoq"],["승강장","perron"],["승객","yo'lovchi"],["추락","qulash"],["의무화(하다)","majburiy qilmoq"],["탈출","qochib chiqish"],
    ["수동","qo'lda boshqarish"],["금연","chekishni tashlash"],["보조제","yordamchi vosita"],["농도","konsentratsiya"],["일회용","bir martalik"],["자제하다","o'zini tiymoq"],
    ["재활용","qayta ishlash"],["반박(하다)","rad qilmoq"],["해롭다","ziyonli"],["과식","ortiqcha ovqatlanish"],["폭식","ochko'zlik bilan yeyish"],["포만감","to'qlik hissi"],
    ["역효과","teskari natija"],["바람직하다","maqbul"],["빈혈","kamqonlik"],["식욕","ishtaha"],["면역","immunitet"],["침입","bosib kirish"],
    ["풍부하다","boy, mo'l"],["대중","omma"],["인물","shaxs, siymo"],["재능","iste'dod"],["신분","tabaqa, martaba"],["지식인","ziyoli"],
    ["식량","oziq-ovqat"],["곡물","don ekini"],["기온","havo harorati"],["수확량","hosil miqdori"],["농업","qishloq xo'jaligi"],["말을 붙이다","gap qotmoq"],
    ["노골적으로","ochiqdan-ochiq"],["출장","xizmat safari"],["눈치가 없다","farqiga bormaydi"],["퉁명스럽다","qo'pol"],["산모","tug'ayotgan ayol"],["출산","tug'ish"],
    ["신생아","chaqaloq"],["양육","bola tarbiyasi"],["요인","sabab, omil"],["액체","suyuqlik"],["생명체","tirik organizm"],["탐사","tadqiqot, izlash"],
    ["행성","sayyora"],["규정","qoida, nizom"],["임금","ish haqi"],["근로자","ishchi"],["고용","bandlik, ishga olish"],["삭감하다","qisqartirmoq"],
    ["창출하다","yaratmoq"],["우려","xavotir"],["효용성","foydalilik"],["반신반의하다","yarim ishonmoq"]
  ] });
