MASTER_WORDS({ id:"tmw-읽기-10", type:"read", label:"TOPIK MASTER 제10회 읽기 so'zlari",
  title:"제10회 읽기", sub:"TOPIK MASTER · 읽기 so'zlari",
  words:[
    ["미루다","kechiktirmoq"],["포기하다","voz kechmoq"],["파고들다","chuqur kirishmoq"],["퇴근하다","ishdan chiqmoq"],["서민","oddiy xalq"],["정책","siyosat"],
    ["내놓다","taklif qilmoq, e'lon qilmoq"],["부딪히다","to'qnash kelmoq"],["두통","bosh og'rig'i"],["치통","tish og'rig'i"],["진통제","og'riq qoldiruvchi dori"],["구입하다","sotib olmoq"],
    ["혜택","imtiyoz, yengillik"],["사라지다","yo'q bo'lmoq"],["장마","yomg'irli mavsum"],["통제되다","to'sib qo'yilmoq"],["교통수단","transport vositasi"],["맞은편","qarshi tomon"],
    ["모시다","kutib olmoq, xizmat qilmoq"],["개업","ochilish, ish boshlash"],["모집","qabul, to'plash"],["분야","soha"],["자격","malaka, huquq"],["이력서","rezyume"],
    ["파견","komandirovkaga yuborish"],["연령","yosh"],["비율","nisbat, foiz"],["실업자","ishsiz"],["개최(하다)","o'tkazmoq"],["기온","havo harorati"],
    ["유지하다","saqlab qolmoq"],["개통되다","ishga tushmoq, ochilmoq"],["인파","odam to'dasi"],["수강","dars olish"],["예매","oldindan bilet olish"],["검색어","qidiruv so'zi"],
    ["확률","ehtimollik"],["보존","saqlash, asrash"],["파손되다","shikastlanmoq"],["유물","qadimiy buyum"],["노인","qariya"],["분류하다","tasniflamoq"],
    ["연금","pensiya"],["규정하다","belgilamoq"],["봄철","bahor fasli"],["증상","alomat"],["지진","zilzila"],["벗어나다","chiqmoq, qutulmoq"],
    ["참사","fojia"],["예측하다","oldindan bilmoq"],["배낭","ryukzak"],["욕심","hirs, nafs"],["고려하다","hisobga olmoq"],["시술","muolaja"],
    ["성형","plastik operatsiya"],["부작용","yon ta'sir"],["주름","ajin"],["일시적","vaqtinchalik"],["낳다","tug'moq"],["빌다","iltijo qilmoq"],
    ["여신","ma'buda"],["자손","avlod, nasl"],["관습","urf-odat"],["찬물을 끼얹다","kayfni buzmoq"],["어깨를 나란히 하다","teng turmoq"],["미술관","san'at muzeyi"],
    ["다가가다","yaqinlashmoq"],["지향하다","maqsad qilmoq"],["답답하다","siqilmoq, dilxun bo'lmoq"],["섭섭하다","ko'ngli qolmoq"],["허무하다","ma'nosiz, bo'm-bo'sh"],["어리석다","ahmoqona"],
    ["두 마리 토끼","ikki maqsad birga"],["시청률","tomoshabin reytingi"],["이민","immigratsiya"],["이주민","ko'chib kelgan"],["위안","tasalli"],["시행착오","sinov va xato"],
    ["해법","yechim"],["눈치가 빠르다","ziyrak"],["몸짓","imo-ishora"],["포착하다","ilg'amoq"],["직관","intuitsiya"],["상대방","suhbatdosh"],
    ["시간대","vaqt oralig'i"],["단적으로","yaqqol"],["영향력","ta'sir kuchi"],["비중","salmoq, ulush"],["온갖","har xil, turli"],["과업","vazifa, topshiriq"],
    ["긴장","zo'riqish, taranglik"],["종결","tugallash"],["욕구","ehtiyoj, istak"],["살아남다","tirik qolmoq"],["생명체","tirik organizm"],["치명적","halokatli"],
    ["노출되다","duchor bo'lmoq"],["극한","o'ta og'ir, ekstremal"],["뿌리다","sepmoq"],["증발되다","bug'lanmoq"],["흡수하다","yutmoq, so'rmoq"],["방출하다","chiqarmoq, ajratmoq"],
    ["터득하다","o'zlashtirmoq"],["독특하다","o'ziga xos"],["짐작하다","chamalamoq"],["체험","sinab ko'rish"],["예절","odob"],["화자","so'zlovchi"],
    ["청자","tinglovchi"],["공손하다","xushmuomala"],["인상","taassurot"],["일관성","izchillik"],["경향","moyillik, tendentsiya"],["제시하다","taqdim etmoq"],
    ["영양소","oziq modda"],["섭취하다","iste'mol qilmoq"],["함유하다","o'z ichiga olmoq"],["해롭다","zararli"],["종사하다","shug'ullanmoq"],["유망하다","istiqbolli"],
    ["직종","kasb turi"],["꼽다","tanlab ko'rsatmoq"],["선발하다","tanlab olmoq"],["효율","samaradorlik"],["무작위","tasodifiy"],["충동적","impulsiv"],
    ["버섯","qo'ziqorin"],["중독","zaharlanish"],["채취","terish, yig'ish"],["오해","tushunmovchilik"],["편견","noto'g'ri qarash"],["개척자","kashshof"],
    ["고집하다","qattiq turib olmoq"],["무대","sahna"],["맷돌","qo'l tegirmoni"],["곡식","don"],["갈다","yanchmoq"],["마찰","ishqalanish"],
    ["주머니","kissa"],["회고하다","xotirlamoq"],["원고","qo'lyozma"],["마지못해","istamay"],["불평등","tengsizlik"],["계층","qatlam"],
    ["재분배","qayta taqsimlash"],["심화되다","chuqurlashmoq"],["일자리","ish joyi"],["발목이 잡히다","qo'l-oyog'i bog'lanmoq"],["수수께끼","jumboq"],["추측","taxmin, faraz"],
    ["실종자","bedarak ketgan"],["중력","tortishish kuchi"],["의문","shubha, savol"],["장학금","stipendiya"],["시행하다","amalga oshirmoq"],["형편","ahvol, sharoit"],
    ["병행하다","birga olib bormoq"],["그림의 떡","yetib bo'lmas narsa"],["투명하다","shaffof"],["납득하다","ishonch hosil qilmoq"]
  ] });
