MASTER_WORDS({ id:"tmw-읽기-8", type:"read", label:"TOPIK MASTER 제8회 읽기 so'zlari",
  title:"제8회 읽기", sub:"TOPIK MASTER · 읽기 so'zlari",
  words:[
    ["최선(을 다하다)","bor kuchini bermoq"],["아쉬움","afsus, armon"],["-는 김에","yo'l-yo'lakay"],["문화재","madaniy meros"],["유적지","tarixiy obida"],["소가죽","mol terisi"],
    ["굽","poshna"],["포장","qadoqlash"],["금고","seyf"],["이삿짐센터","ko'chirish xizmati"],["정책","siyosat"],["쌀쌀하다","salqin"],
    ["일교차","kunlik harorat farqi"],["예방 접종","emlash"],["통제하다","nazorat qilmoq"],["개방","ochiqlik, ochish"],["입장료","kirish to'lovi"],["재현하다","qayta gavdalantirmoq"],
    ["생활비","yashash xarajati"],["분포","taqsimot"],["액수","pul summasi"],["불황","iqtisodiy tanglik"],["열풍","qizg'in moda"],["-에도 불구하고","qaramasdan"],
    ["사치","hashamat, dabdaba"],["감상하다","zavq bilan tomosha qilmoq"],["몰입","berilib ketish"],["가늠하다","chamalamoq"],["가상 현실","virtual reallik"],["입체","hajmli, uch o'lchovli"],
    ["생생하다","yorqin, tirikdek"],["음주 운전","mast holda haydash"],["단속","nazorat, tekshiruv"],["논란","bahs-munozara"],["편식하다","tanlab ovqatlanmoq"],["섭취하다","iste'mol qilmoq"],
    ["치우치다","bir tomonga og'moq"],["균형","muvozanat"],["습기","namlik"],["흡수하다","shimmoq"],["부품","detal, qism"],["안락사","evtanaziya"],
    ["허용하다","ruxsat bermoq"],["수용하다","qabul qilmoq"],["존엄성","qadr-qimmat"],["확산되다","keng tarqalmoq"],["훼손하다","zarar yetkazmoq"],["우려","xavotir"],
    ["민폐","boshqalarga noqulaylik"],["비로소","shundagina"],["해방","ozodlik"],["성차별","jinsiy kamsitish"],["가부장적","patriarxal"],["이념","mafkura"],
    ["평등하다","teng huquqli"],["천 리 길도 한 걸음부터","har ish boshidan"],["울며 겨자 먹기","iloj yo'qlikdan qilmoq"],["원리","asosiy qonuniyat"],["차근차근","bosqichma-bosqich"],["조급하다","shoshqaloq"],
    ["설레다","hayajonlanmoq"],["첫사랑","birinchi muhabbat"],["휘파람","hushtak"],["콩닥거리다","duk-duk urmoq"],["수줍음","uyatchanlik"],["물 폭탄","kuchli jala"],
    ["구별되다","farqlanmoq"],["출항","suzib chiqish"],["용돈","cho'ntak puli"],["연금","pensiya"],["개혁","islohot"],["산수화","sharqona manzara rasmi"],
    ["풍경화","peyzaj"],["묘사","tasvirlash"],["빗대다","qiyoslab ifodalamoq"],["함유하다","tarkibida bo'lmoq"],["일으키다","keltirib chiqarmoq"],["심장마비","yurak xuruji"],
    ["임금","ish haqi"],["삭감하다","qisqartirmoq"],["정년","nafaqa yoshi"],["도입하다","joriy qilmoq"],["근로자","ishchi, xodim"],["부담감","mas'uliyat yuki"],
    ["중시되다","muhim sanalmoq"],["소비자","iste'molchi"],["좌우되다","bog'liq bo'lmoq"],["백열전구","cho'g'lanma lampa"],["효율","samaradorlik"],["수명","xizmat muddati"],
    ["전력","elektr quvvati"],["형광등","lyuminesent lampa"],["물리다","tishlanmoq"],["부위","tana joyi"],["통증","og'riq"],["퍼지다","yoyilmoq"],
    ["제거하다","olib tashlamoq"],["하층민","quyi tabaqa"],["고단하다","mashaqqatli"],["달래다","yupatmoq"],["멸시하다","mensimaslik"],["전성기","gullab-yashnash davri"],
    ["한류","Koreya to'lqini"],["열광하다","jazavaga tushmoq"],["경쟁력","raqobatbardoshlik"],["식상하다","siyqalashmoq"],["창출하다","yaratmoq"],["벗어나다","qutulmoq"],
    ["실직","ishsiz qolish"],["부정적","salbiy"],["악순환","yomon aylanma"],["노안","ko'z qarishi"],["시력","ko'rish qobiliyati"],["회복하다","tiklanmoq"],
    ["능률","ish unumi"],["무릎","tizza"],["혈액 순환","qon aylanishi"],["관절","bo'g'im"],["이완되다","bo'shashmoq"],["신진대사","moddalar almashinuvi"],
    ["두통","bosh og'rig'i"],["진통제","og'riq qoldiruvchi"],["시달리다","qiynalmoq"],["과용","ortiqcha ishlatish"],["뿌듯하다","iftixor qilmoq"],["연설","nutq"],
    ["외교관","diplomat"],["신중하다","ehtiyotkor"],["정전기","statik elektr"],["마찰","ishqalanish"],["물체","jism"],["저장되다","to'planmoq"],
    ["-기 마련이다","bo'lishi tabiiy"],["당황스럽다","dovdirab qolmoq"],["그리워하다","sog'inmoq"],["하염없이","tinimsiz, uzoq"],["서글프다","g'amgin"],["일벌레","ishga berilgan odam"],
    ["무작정","o'ylamasdan"],["왜곡","buzib ko'rsatish"],["해석","talqin"],["검증되다","tekshirilmoq"],["정체성","o'zlik, identitet"],["중립성","betaraflik"],
    ["바람직하다","maqbul"],["주장하다","da'vo qilmoq"],["지능","aql darajasi"],["고래","kit"],["비율","nisbat, ulush"],["차지하다","egallamoq"],
    ["대뇌","katta miya"],["필자","muallif"],["할당제","kvota tizimi"],["촉구하다","undamoq"],["지적하다","ko'rsatib bermoq"],["고용","ishga olish"],
    ["승진","lavozimda ko'tarilish"],["조치","chora, tadbir"],["위상","obro', maqom"],["역차별","teskari kamsitish"]
  ] });
