MASTER_WORDS({ id:"tmw-읽기-9", type:"read", label:"TOPIK MASTER 제9회 읽기 so'zlari",
  title:"제9회 읽기", sub:"TOPIK MASTER · 읽기 so'zlari",
  words:[
    ["형편","ahvol, sharoit"],["속마음","dildagi gap"],["털어놓다","dilini yormoq"],["행동","xatti-harakat"],["단순하다","oddiy, sodda"],["쾌적하다","shinam, yoqimli"],
    ["수면","uyqu"],["보양식","quvvat beruvchi taom"],["질서","tartib"],["인격","insoniy qadr, odob"],["공익","umumiy manfaat"],["문의","so'rov, murojaat"],
    ["포장(하다)","qadoqlash"],["주민","aholi, mahalla ahli"],["수강료","o'quv to'lovi"],["거주하다","istiqomat qilmoq"],["환자","bemor"],["분포","taqsimot, tarqalish"],
    ["격차","tafovut, farq"],["근로자","ishchi, xodim"],["휴일","dam olish kuni"],["수당","ustama haq"],["그림의 떡","erishilmas narsa"],["유행하다","moda bo'lmoq"],
    ["우정","do'stlik"],["앞두다","oldida turmoq"],["부착되다","o'rnatilmoq"],["차단(하다)","to'sish, bloklash"],["투명하다","shaffof"],["축제","festival, bayram"],
    ["개최되다","o'tkazilmoq"],["기원하다","tilamoq, duo qilmoq"],["자살","o'z joniga qasd"],["연관성","bog'liqlik"],["미세 먼지","mayda chang"],["호흡기","nafas yo'llari"],
    ["우울증","depressiya"],["초점","diqqat markazi"],["타인","o'zga odam"],["집착하다","berilib ketmoq"],["단단하다","qattiq, mustahkam"],["세월","yillar, davr"],
    ["공경하다","hurmat qilmoq"],["권력","hokimiyat"],["우주선","kosmik kema"],["무중력","vaznsizlik"],["근육","mushak"],["그럼에도 불구하고","shunga qaramay"],
    ["도저히","hech, umuman"],["속담","maqol"],["긍정적","ijobiy"],["부정적","salbiy"],["교훈","saboq, ibrat"],["근면하다","mehnatkash, tirishqoq"],
    ["땅 짚고 헤엄치기","juda oson ish"],["육체적","jismoniy"],["정신적","ruhiy, ma'naviy"],["섭취하다","iste'mol qilmoq"],["우려","xavotir, tashvish"],["당황스럽다","esankiragan, shoshgan"],
    ["실수","xato"],["반복하다","takrorlamoq"],["조언","maslahat"],["어리둥절하다","dovdirab qolmoq"],["생계","tirikchilik"],["외면하다","yuz o'girmoq"],
    ["임금","ish haqi"],["액수","summa, miqdor"],["사용자","ish beruvchi"],["행선지","boradigan manzil"],["묵묵부답","sukut, javobsizlik"],["장거리","uzoq masofa"],
    ["증시","fond bozori"],["항공","aviatsiya"],["마비되다","falaj bo'lmoq"],["직업","kasb"],["생명","hayot, jon"],["배려하다","g'amxo'rlik qilmoq"],
    ["윤리적","axloqiy"],["만화","komiks"],["재현하다","aks ettirmoq"],["설득하다","ishontirmoq"],["오락","o'yin-kulgi"],["편성되다","jadvalga kiritilmoq"],
    ["시청률","tomosha reytingi"],["좌우하다","belgilab bermoq"],["상업성","tijoriylik"],["소설가","yozuvchi"],["광복","ozodlik, mustaqillik"],["겪다","boshdan kechirmoq"],
    ["수난","azob-uqubat"],["묘사하다","tasvirlamoq"],["상품","tovar"],["적합하다","mos, munosib"],["성능","ish qobiliyati"],["신뢰성","ishonchlilik"],
    ["통증","og'riq"],["치명적","halokatli"],["자극","qo'zg'atish, ta'sir"],["신경","nerv, asab"],["보완하다","to'ldirmoq"],["선보이다","namoyish etmoq"],
    ["품종","nav, sort"],["어우러지다","uyg'unlashmoq"],["전망","istiqbol, kutilish"],["청년","yoshlar"],["일자리","ish joyi"],["숙련되다","malakali bo'lmoq"],
    ["기술자","texnik mutaxassis"],["실업","ishsizlik"],["인력난","kadr tanqisligi"],["한자어","xitoycha so'z"],["차지하다","egallamoq"],["의사소통","muloqot"],
    ["구분하다","ajratmoq, farqlamoq"],["구강","og'iz bo'shlig'i"],["당뇨병","qandli diabet"],["구취","og'iz hidi"],["의심하다","shubhalanmoq"],["주택","uy-joy"],
    ["해롭다","zararli"],["시달리다","azob chekmoq"],["환기","shamollatish"],["대책","chora-tadbir"],["경신하다","rekordni yangilamoq"],["임시직","vaqtinchalik ish"],
    ["정규직","doimiy ish"],["악화되다","yomonlashmoq"],["구절","satr, band"],["시인","shoir"],["강렬하다","kuchli, yorqin"],["조국","vatan"],
    ["간절하다","chin dildan"],["애국심","vatanparvarlik"],["어이없다","aql bovar qilmas"],["유래","kelib chiqish"],["황당하다","bema'ni, g'alati"],["태도","munosabat, xulq"],
    ["너그럽다","kechirimli, saxiy"],["뻔뻔하다","uyatsiz"],["승객","yo'lovchi"],["양보하다","joy bermoq"],["사양하다","tortinib rad etmoq"],["난임","bepushtlik"],
    ["정책","siyosat"],["출산","tug'ish"],["배아","embrion"],["제한하다","cheklamoq"],["지능","aql, intellekt"],["창의적","ijodiy"],
    ["능숙하다","mohir, chaqqon"],["유전","irsiyat"],["필자","muallif"],["규정","qoida, nizom"],["설치하다","o'rnatmoq"],["의무화되다","majburiy qilinmoq"],
    ["치사율","o'lim darajasi"],["실효성","amaliy samara"],["회의적","skeptik, ishonchsiz"],["목숨을 걸다","jonini garovga qo'ymoq"]
  ] });
