MASTER_WORDS({ id:"tmw-읽기-4", type:"read", label:"TOPIK MASTER 제4회 읽기 so'zlari",
  title:"제4회 읽기", sub:"TOPIK MASTER · 읽기 so'zlari",
  words:[
  ["간호하다","parvarish qilmoq"],["유학생","chet ellik talaba"],["날로","kundan-kunga"],["증가하다","ortmoq, ko'paymoq"],["기 마련이다","bo'lishi tabiiy"],["초고속","o'ta tezkor"],
  ["화제","muhokama mavzusi"],["감상하다","tomosha qilmoq, zavqlanmoq"],["호기심","qiziquvchanlik"],["현장 학습","joyida o'tkaziladigan mashg'ulot"],["탑승하다","minmoq, chiqmoq"],["주의 사항","ehtiyot choralari"],
  ["도자기","sopol buyum"],["전시회","ko'rgazma"],["교환권","almashtirish kuponi"],["유효 기간","amal qilish muddati"],["매표소","kassa"],["환불","pulni qaytarish"],
  ["장수","uzoq umr"],["비결","siri, usuli"],["식습관","ovqatlanish odati"],["낙천적","optimistik"],["꼽다","tanlab ko'rsatmoq"],["요금","to'lov, tarif"],
  ["인상되다","oshirilmoq"],["동결되다","o'zgarmay qolmoq"],["승객","yo'lovchi"],["소매상인","chakana sotuvchi"],["성황을 이루다","gavjum bo'lmoq"],["업계","soha, tarmoq"],
  ["경쟁력","raqobatbardoshlik"],["설상가상","balo ustiga balo"],["급감하다","keskin kamaymoq"],["해발","dengiz sathidan balandlik"],["요새","istehkom, qal'a"],["문화유산","madaniy meros"],
  ["등재되다","ro'yxatga kiritilmoq"],["보행","piyoda yurish"],["횡단보도","piyodalar o'tish joyi"],["배려하다","g'amxo'rlik qilmoq"],["먹이","yem"],["뛰어들다","sho'ng'imoq, otilib kirmoq"],
  ["머뭇거리다","taraddudlanmoq"],["천적","tabiiy dushman"],["착각하다","yanglishmoq"],["증후군","sindrom"],["부딪히다","duch kelmoq"],["타인","o'zga kishi"],
  ["결핍","kamchilik, yetishmovchilik"],["과잉","ortiqcha, haddan ziyod"],["극복하다","engmoq"],["재능","iste'dod"],["과연","haqiqatan ham"],["확산되다","tarqalmoq"],
  ["비롯되다","kelib chiqmoq"],["외모","tashqi ko'rinish"],["편협하다","tor fikrli"],["가치관","qadriyatlar tizimi"],["색안경을 끼고 보다","noxolis qaramoq"],["수집가","kolleksioner"],
  ["미술품","san'at buyumi"],["명작","shoh asar"],["사치스럽다","dabdabali"],["염두에 두다","hisobga olmoq"],["어이없다","mantiqsiz, kulgili"],["간판","lavha, peshtaxta"],
  ["망원경","durbin"],["간직하다","saqlamoq"],["옥상","tom, ustki qavat"],["불황","turg'unlik, inqiroz"],["초래하다","keltirib chiqarmoq"],["생태계","ekotizim"],
  ["파괴","vayron qilish"],["주범","asosiy aybdor"],["일자리","ish joyi"],["동원하다","jalb qilmoq"],["허사","behuda urinish"],["특가품","chegirmali mahsulot"],
  ["절약하다","tejamoq"],["손해","zarar"],["유인하다","o'ziga tortmoq"],["깜박거리다","pirpiratmoq"],["확신","qat'iy ishonch"],["인과 관계","sababiy bog'liqlik"],
  ["생소하다","notanish"],["장애인","nogiron"],["중증","og'ir darajali"],["재활","reabilitatsiya"],["표적","nishon"],["무역","savdo"],
  ["풍력","shamol kuchi"],["건축물","inshoot, bino"],["바람개비","parrak"],["공급하다","ta'minlamoq"],["친환경","ekologik"],["개념","tushuncha"],
  ["우호적","do'stona"],["적대적","dushmanona"],["점술가","folbin"],["창의적","ijodkor"],["두려움","qo'rquv"],["망설이다","ikkilanmoq"],
  ["효율성","samaradorlik"],["시행착오","xato va urinish"],["감수하다","tavakkal qilmoq"],["권장량","tavsiya etilgan miqdor"],["미달하다","miqdorga yetmaslik"],["섭취하다","iste'mol qilmoq"],
  ["육류","go'sht mahsulotlari"],["성인병","kattalar kasalligi"],["저작물","muallif asari"],["허락","ruxsat"],["표절","plagiat"],["저작권","mualliflik huquqi"],
  ["침해하다","tajovuz qilmoq"],["처벌","jazo"],["모기","chivin"],["물리다","chaqilmoq"],["방충망","chivin to'ri"],["차단하다","to'smoq"],
  ["탈수증","suvsizlanish"],["예방하다","oldini olmoq"],["격렬하다","shiddatli"],["수분","namlik, suyuqlik"],["보충하다","to'ldirmoq"],["작곡하다","kuy yozmoq"],
  ["악보","nota"],["성악가","vokalchi"],["정평이 나다","tan olingan bo'lmoq"],["경악하다","hayratdan qolmoq"],["동영상","video"],["압축","siqish"],
  ["중복","takrorlanish"],["괘씸하다","g'ashi kelmoq"],["안쓰럽다","rahmi kelmoq"],["원고료","qalam haqi"],["연재하다","bo'lib-bo'lib chop etmoq"],["딱하다","achinarli"],
  ["아른거리다","ko'z oldida jonlanmoq"],["혼수","sep"],["부담하다","o'z ustiga olmoq"],["주택","uy-joy"],["의지하다","suyanmoq"],["신혼부부","yangi turmush qurganlar"],
  ["편견","noto'g'ri qarash"],["복지","ijtimoiy ta'minot"],["주거","turar joy"],["정책","siyosat"],["급증","keskin o'sish"],["실업","ishsizlik"],
  ["빈곤","qashshoqlik"],["개선되다","yaxshilanmoq"],["필자","muallif"],["경각심","hushyorlik"],["일깨우다","uyg'otmoq"],["공공연하다","ochiqdan-ochiq"],
  ["드러내다","oshkor qilmoq"],["촉구하다","talab qilmoq"],["훼손하다","obro'siga tegmoq"],["비방하다","tuhmat qilmoq"]
] });
