MASTER_WORDS({ id:"tmw-읽기-1", type:"read", label:"TOPIK MASTER 제1회 읽기 so'zlari",
  title:"제1회 읽기", sub:"TOPIK MASTER · 읽기 so'zlari",
  words:[
    ["취업","ishga kirish"],["외모","tashqi ko'rinish"],["-에도 불구하고","qaramasdan"],["-곤 하다","qilib turmoq"],["황사","sariq chang bo'roni"],["화재","yong'in"],
    ["발생(하다)","yuz berish"],["불우하다","kambag'al, baxtsiz"],["기부금","xayriya puli"],["품질","sifat"],["영화제","kinofestival"],["상영(하다)","namoyish qilish"],
    ["개막식","ochilish marosimi"],["여가","bo'sh vaqt"],["기피하다","chetlab o'tmoq"],["졸음운전","uyquli haydash"],["위험성","xavflilik"],["대대적","keng ko'lamli"],
    ["예방하다","oldini olmoq"],["소극적","sust, passiv"],["무너지다","qulamoq"],["현상","hodisa"],["지진","zilzila"],["대책","chora-tadbir"],
    ["예측","bashorat"],["세금","soliq"],["창업(하다)","biznes boshlash"],["업종","faoliyat turi"],["확률","ehtimollik"],["흔들다","silkitmoq"],
    ["귀갓길","uyga qaytish yo'li"],["책임지다","javobgar bo'lmoq"],["설치하다","o'rnatmoq"],["한옥","an'anaviy koreys uyi"],["볼거리","tomosha joyi"],["매력적","jozibali"],
    ["강좌","kurs"],["배경","fon"],["저절로","o'z-o'zidan"],["원리","tamoyil"],["죽음","o'lim"],["마무리하다","yakunlamoq"],
    ["소중하다","qadrli"],["목적","maqsad"],["직장인","ish xizmatchisi"],["소비","iste'mol"],["오히려","teskarisiga"],["반면","boshqa tomondan"],
    ["식습관","ovqatlanish odati"],["구직자","ish izlovchi"],["취업난","ishga kirish qiyinligi"],["합격","imtihondan o'tish"],["채용","ishga qabul qilish"],["공개하다","ommaga e'lon qilmoq"],
    ["꺼리다","istamaslik"],["차라리","yaxshisi"],["인류","insoniyat"],["이익","foyda"],["양날의 칼","ikki tomoni o'tkir qilich"],["눈살을 찌푸리다","qovog'ini uymoq"],
    ["노약자석","imtiyozli o'rindiq"],["무심코","beixtiyor"],["배려","g'amxo'rlik"],["창피하다","uyalmoq"],["얼어붙다","muzlab qolmoq"],["건축","qurilish"],
    ["경기","iqtisodiy holat"],["할인","chegirma"],["가출","uydan qochish"],["악기","musiqa asbobi"],["문지르다","ishqalamoq"],["파동","to'lqin"],
    ["퍼지다","tarqalmoq"],["구성하다","tashkil etmoq"],["문단","abzas"],["독해","o'qib tushunish"],["추론하다","xulosa chiqarmoq"],["일자리","ish joyi"],
    ["부족하다","yetishmaslik"],["정규직","doimiy ishchi"],["양극화","qutblashish"],["임금","ish haqi"],["격차","tafovut"],["실업","ishsizlik"],
    ["불안감","xavotir"],["연인","sevishganlar"],["수치","ko'rsatkich"],["우울증","depressiya"],["식품","oziq-ovqat"],["출산율","tug'ilish darajasi"],
    ["인구","aholi"],["차지하다","egallamoq"],["장악하다","qo'lga olmoq"],["글씨체","shrift"],["가독성","o'qilish qulayligi"],["단정하다","ozoda, tartibli"],
    ["간판","peshlavha"],["설립되다","tashkil etilmoq"],["원조","yordam"],["모금","mablag' yig'ish"],["후원","homiylik"],["숙면","chuqur uyqu"],
    ["방해하다","xalaqit bermoq"],["자세","holat, poza"],["통증","og'riq"],["유발하다","keltirib chiqarmoq"],["빚","qarz"],["부동산","ko'chmas mulk"],
    ["정책","siyosat"],["서민","oddiy xalq"],["대출","kredit"],["소득","daromad"],["재앙","falokat"],["거르다","o'tkazib yubormoq"],
    ["섭취","ovqat qabul qilish"],["중독","qaramlik"],["굶다","och yurmoq"],["보상","mukofot"],["배출","chiqarish"],["조작","qalbakilashtirish"],
    ["환경","atrof-muhit"],["소비자","iste'molchi"],["밝히다","oshkor qilmoq"],["평균","o'rtacha"],["자살","o'z joniga qasd qilish"],["충동","turtki, impuls"],
    ["보충하다","qoplamoq"],["신기록","yangi rekord"],["완벽하다","mukammal"],["관객","tomoshabin"],["영양소","ozuqa moddasi"],["곡물","don mahsuloti"],
    ["볶다","qovurmoq"],["국","sho'rva"],["반찬","yon taom"],["집착","berilib ketish"],["간장","soya sousi"],["싱겁다","tuzsiz"],
    ["식욕","ishtaha"],["기가 막히다","hayratdan lol qolmoq"],["강요하다","majburlamoq"],["피로","charchoq"],["분석","tahlil"],["집중력","diqqat jamlash"],
    ["능률","samaradorlik"],["조정하다","moslashtirmoq"],["기상","ob-havo"],["어민","baliqchi"],["해류","dengiz oqimi"],["어획량","baliq ovi hajmi"],
    ["폭염","jazirama"],["가뭄","qurg'oqchilik"],["예금","omonat"],["금융","moliya"],["고객","mijoz"],["제도","tizim, tartib"],
    ["저축","jamg'arma"],["원금","asosiy summa"],["이자","foiz"],["필자","muallif"]
  ] });
