MASTER_WORDS({ id:"tmw-읽기-6", type:"read", label:"TOPIK MASTER 제6회 읽기 so'zlari",
  title:"제6회 읽기", sub:"TOPIK MASTER · 읽기 so'zlari",
  words:[
    ["전화벨","telefon qo'ng'irog'i"],["울리다","jiringlamoq"],["-는 탓에","sababli"],["다짐하다","qat'iy qaror qilmoq"],["합격하다","imtihondan o'tmoq"],["취직하다","ishga kirmoq"],
    ["신선하다","yangi, toza"],["상하다","aynimoq"],["농산물","dehqonchilik mahsuloti"],["수산물","baliq mahsuloti"],["추첨","qur'a tashlash"],["저소득층","kam ta'minlangan qatlam"],
    ["독소","toksin, zahar"],["제거하다","yo'q qilmoq"],["저항력","qarshilik kuchi"],["효능","shifobaxsh ta'sir"],["열정","shijoat, ehtiros"],["자원봉사자","ko'ngilli"],
    ["모집","to'plash, qabul"],["통역","og'zaki tarjima"],["불리하다","noqulay"],["가구","uy xo'jaligi"],["규모","hajm, miqyos"],["추세","tendensiya"],
    ["해녀","ayol g'avvos"],["채취하다","terib olmoq"],["고령","keksa yosh"],["감소하다","kamaymoq"],["등재하다","ro'yxatga kiritmoq"],["원동력","harakatlantiruvchi kuch"],
    ["향상되다","yaxshilanmoq"],["상승하다","ko'tarilmoq"],["수치","raqamli ko'rsatkich"],["실업률","ishsizlik darajasi"],["공무원","davlat xizmatchisi"],["청년","yoshlar"],
    ["공통점","umumiy jihat"],["원천","manba, asos"],["국방부","mudofaa vazirligi"],["특허권","patent huquqi"],["고집하다","o'jarlik qilmoq"],["민간","nodavlat, xususiy"],
    ["출현하다","namoyon bo'lmoq"],["감염성","yuqumli"],["질환","kasallik"],["위생","gigiena"],["안정되다","barqarorlashmoq"],["용돈","cho'ntak puli"],
    ["인식하다","anglamoq, deb bilmoq"],["취업","ishga joylashish"],["한파","sovuq to'lqini"],["억지로","majburan"],["경력","ish tajribasi"],["생계","tirikchilik"],
    ["수단","vosita"],["조화","uyg'unlik"],["편견","noto'g'ri qarash"],["감정","hissiyot"],["인공 지능","sun'iy intellekt"],["조절하다","boshqarmoq, moslamoq"],
    ["회의적","shubhali"],["태도","munosabat, yondashuv"],["지하자원","yer osti boyliklari"],["퇴적물","cho'kindi"],["기후","iqlim"],["방대하다","nihoyatda katta"],
    ["가라앉다","cho'kmoq"],["번성하다","gullab-yashnamoq"],["유추하다","taxmin qilmoq"],["속담","maqol"],["상대방","suhbatdosh"],["입장","nuqtai nazar"],
    ["오해","tushunmovchilik"],["-기 마련이다","bo'lishi tabiiy"],["심정","ruhiy holat"],["뿌듯하다","mamnun bo'lmoq"],["안타깝다","achinarli"],["권유","undash, taklif"],
    ["적성","moyillik"],["망설이다","ikkilanmoq"],["귀 기울이다","quloq solmoq"],["양복","kostyum"],["평상복","kundalik kiyim"],["허물다","buzmoq, yo'q qilmoq"],
    ["옷차림","kiyinish tarzi"],["내리막길","pasayish, tanazzul"],["매출","savdo tushumi"],["대폭","keskin, ancha"],["대사","dialog matni"],["용납하다","yo'l qo'ymoq"],
    ["지위","maqom"],["부상","jarohat"],["차지하다","egallamoq"],["사고방식","fikrlash tarzi"],["선호하다","afzal ko'rmoq"],["독자","o'quvchi"],
    ["치열하다","shiddatli"],["왜곡","buzib ko'rsatish"],["호기심","qiziquvchanlik"],["외래종","kelgindi tur"],["천적","tabiiy dushman"],["생태계","ekotizim"],
    ["위협하다","tahdid qilmoq"],["마비시키다","falajlamoq"],["손실","zarar, yo'qotish"],["거래","savdo, bitim"],["출처","kelib chiqish manbasi"],["선비","ziyoli, olim"],
    ["계층","qatlam"],["풍조","urf, oqim"],["용기","jasorat"],["감수하다","bardosh bermoq"],["항생제","antibiotik"],["오남용","noto'g'ri ishlatish"],
    ["내성","chidamlilik"],["창작물","ijod asari"],["상상력","tasavvur"],["의도","niyat"],["우려","xavotir"],["안보","xavfsizlik"],
    ["통일","birlashish"],["시급하다","shoshilinch"],["교류","almashinuv"],["대책","chora-tadbir"],["모순","qarama-qarshilik"],["양치질","tish tozalash"],
    ["삼가다","tiyilmoq"],["보관하다","saqlamoq"],["식중독","ovqatdan zaharlanish"],["검출되다","aniqlanmoq"],["만끽하다","to'liq bahra olmoq"],["해설","izoh, sharh"],
    ["신어","yangi so'z"],["외래어","o'zlashma so'z"],["인색하다","qizg'anchiq"],["자상하다","mehribon"],["종업원","xizmat ko'rsatuvchi"],["가로등","ko'cha chirog'i"],
    ["투숙객","mehmon, yashovchi"],["귀찮다","erinmoq, zerikarli"],["시간을 끌다","vaqtni cho'zmoq"],["꺼리다","tortinmoq"],["감탄하다","hayratlanmoq"],["성취","erishilgan natija"],
    ["모국어","ona tili"],["확산","tarqalish"],["촬영","suratga olish"],["범죄","jinoyat"],["유포하다","tarqatmoq"],["차단하다","to'smoq"],
    ["조치","tadbir, qadam"],["행위","xatti-harakat"],["간접흡연","passiv chekish"],["규제","cheklov"],["악영향","salbiy ta'sir"],["지적","ko'rsatib o'tish, tanqid"],
    ["독성","zaharlilik"],["농도","quyuqlik, konsentratsiya"],["치명적","halokatli"],["축적되다","to'planmoq"],["노출","ta'sirga uchrash"],["금연","chekishni tashlash"],
    ["폐해","zararli oqibat"]
  ] });
