MASTER_WORDS({ id:"tmw-읽기-5", type:"read", label:"TOPIK MASTER 제5회 읽기 so'zlari",
  title:"제5회 읽기", sub:"TOPIK MASTER · 읽기 so'zlari",
  words:[
    ["노인","qariya, keksa"],["취업","ishga joylashish"],["설문 조사","so'rovnoma"],["과반수","yarmidan ko'pi"],["전망","manzara, istiqbol"],["편리하다","qulay"],
    ["-을 뿐만 아니라","nafaqat, balki"],["전공","mutaxassislik"],["자외선","ultrabinafsha nur"],["차단","to'sish, himoya"],["연고","malham"],["실화","haqiqiy voqea"],
    ["원작","asl asar"],["평론가","tanqidchi"],["극찬","yuqori maqtov"],["수명","umr davomiyligi"],["은퇴","nafaqaga chiqish"],["선진국","rivojlangan davlat"],
    ["노후","qarilik davri"],["구입","sotib olish"],["상표","yorliq, brend"],["교환","almashtirish"],["반품","tovarni qaytarish"],["공모전","ijodiy tanlov"],
    ["접수","qabul qilish"],["시상","mukofotlash"],["투표","ovoz berish"],["거주(하다)","istiqomat qilmoq"],["근로자","ishchi"],["이민자","muhojir"],
    ["비율","nisbat, foiz"],["도입(되다)","joriy etmoq"],["능동적","faol, tashabbuskor"],["취지","maqsad, mohiyat"],["정책","siyosat"],["치우치다","bir tomonga og'moq"],
    ["균형","muvozanat"],["대륙","qit'a"],["편견","noto'g'ri qarash"],["상식","umumiy bilim"],["혈관","qon tomiri"],["착각","yanglishish"],
    ["위험에 처하다","xavf ostida qolmoq"],["핵심","asosiy nuqta"],["비결","sir, usul"],["밝혀내다","oshkor qilmoq"],["인재","iste'dodli kadr"],["초소형","o'ta kichik"],
    ["주택","turar joy"],["절차","tartib, protsedura"],["장점","afzallik"],["공평하다","adolatli, teng"],["선택권","tanlash huquqi"],["양보하다","yo'l bermoq"],
    ["나무꾼","o'tinchi"],["알아채다","sezib qolmoq"],["주저앉다","cho'kib o'tirmoq"],["무조건","so'zsiz, shartsiz"],["교통량","transport oqimi"],["과속","tezlikni oshirish"],
    ["야생","yovvoyi"],["성과","natija, samara"],["자칫","beixtiyor, ehtiyotsizlikdan"],["개성","o'ziga xoslik"],["주체적","mustaqil"],["전략","strategiya"],
    ["-기 십상이다","bo'lishi ehtimoli katta"],["두 마리 토끼를 잡다","ikki quyonni birga ovlamoq"],["가사","uy ishlari"],["분담하다","taqsimlab olmoq"],["성차별","jinsiy kamsitish"],["심정","ruhiy holat"],
    ["안쓰럽다","achinarli"],["서운하다","ranjigan"],["독감","gripp"],["다문화","ko'p madaniyatlilik"],["기업","korxona"],["업무","ish, vazifa"],
    ["서면","yozma hujjat"],["대체하다","o'rnini bosmoq"],["이사철","ko'chish mavsumi"],["전셋값","ijara garovi narxi"],["추세","tendensiya"],["가구","xonadon"],
    ["간편하다","sodda, oson"],["주가","aksiya narxi"],["식품","oziq-ovqat"],["곤충","hasharot"],["배설물","najas"],["취향","did, xohish"],
    ["선호하다","afzal ko'rmoq"],["예술","san'at"],["무대","sahna"],["분야","soha"],["종합하다","jamlamoq"],["순하다","mo'min, yumshoq"],
    ["영리하다","zehnli"],["충성심","sadoqat"],["희생하다","qurbon qilmoq"],["판사","sudya"],["판결","hukm"],["경향","moyillik, tamoyil"],
    ["보수적","konservativ"],["박쥐","ko'rshapalak"],["초음파","ultratovush"],["파악하다","tushunib olmoq"],["민감하다","sezgir"],["작품","asar"],
    ["번지다","yoyilmoq, tarqalmoq"],["소재","mavzu, material"],["발음","talaffuz"],["어법","til qoidasi"],["이중 언어","ikki tillilik"],["반영되다","aks etmoq"],
    ["보육","bolalarni parvarishlash"],["간과하다","e'tiborsiz qoldirmoq"],["비정규직","nodoimiy ish"],["확충하다","kengaytirmoq"],["기기","qurilma"],["시력","ko'rish qobiliyati"],
    ["악영향","salbiy ta'sir"],["현저히","sezilarli darajada"],["개혁","isloh"],["부실","puch, sifatsiz"],["법안","qonun loyihasi"],["근거","asos, dalil"],
    ["신호","signal"],["섭취하다","iste'mol qilmoq"],["축적되다","to'planmoq"],["만성병","surunkali kasallik"],["다량","ko'p miqdor"],["단백질","oqsil"],
    ["소화","hazm"],["부작용","yon ta'sir"],["천식","astma"],["이겨내다","yengib o'tmoq"],["격차","tafovut"],["열악하다","og'ir, yomon"],
    ["나아가다","oldinga siljimoq"],["일치하다","mos tushmoq"],["마찰력","ishqalanish kuchi"],["서서히","sekin-asta"],["홀가분하다","yengil tortmoq"],["흐뭇하다","mamnun"],
    ["자부심","g'urur"],["좀처럼","kamdan-kam"],["억제하다","bosib turmoq"],["우울증","depressiya"],["포만감","to'qlik hissi"],["노화","qarish"],
    ["자존감","o'z qadri"],["요인","omil"],["세대","avlod"],["포기하다","voz kechmoq"],["등록금","o'quv to'lovi"],["용어","atama"],
    ["시달리다","azob chekmoq"],["강사","o'qituvchi"],["고용","ishga olish"],["촉구하다","talab qilmoq"],["지적하다","ta'kidlab ko'rsatmoq"],["걸림돌","to'siq"],
    ["양성하다","tayyorlamoq"],["좌우하다","belgilamoq, hal qilmoq"]
  ] });
