MASTER_WORDS({ id:"tmw-읽기-7", type:"read", label:"TOPIK MASTER 제7회 읽기 so'zlari",
  title:"제7회 읽기", sub:"TOPIK MASTER · 읽기 so'zlari",
  words:[
    ["차라리","yaxshisi, aksincha"],["평생","umr bo'yi"],["제외하다","hisobdan chiqarmoq"],["-기 마련이다","bo'lishi tabiiy"],["영양분","oziq modda"],["정수기","suv tozalagich"],
    ["자산","aktiv, boylik"],["세계화","globallashuv"],["교류","almashinuv, aloqa"],["다문화","ko'p madaniyatli"],["보관(하다)","saqlash"],["무형유산","nomoddiy meros"],
    ["선정(하다)","tanlab olish"],["사교육비","qo'shimcha ta'lim xarajati"],["지출하다","xarajat qilmoq"],["핵심","asosiy, o'zak"],["노년층","qariyalar qatlami"],["격차","tafovut, farq"],
    ["손주","nabira"],["육아","bola tarbiyasi"],["무인","odamsiz, boshqaruvchisiz"],["조종","boshqaruv, rul"],["상용화","keng iste'molga chiqarish"],["빈도","takrorlanish soni"],
    ["파악(하다)","anglab olish"],["근육","mushak"],["콩팥","buyrak"],["과도하다","haddan ziyod"],["사망률","o'lim darajasi"],["산림","o'rmon"],
    ["재해","tabiiy ofat"],["취약하다","zaif, nochor"],["산사태","ko'chki"],["출산율","tug'ilish darajasi"],["능가하다","ustun kelmoq"],["비중","salmoq, ulush"],
    ["갈대","qamish"],["거세다","kuchli, shiddatli"],["흔들리다","chayqalmoq, tebranmoq"],["부러지다","sinmoq"],["버티다","dosh bermoq"],["습득하다","egallab olmoq"],
    ["구성원","a'zo"],["규범","norma, qoida"],["상호작용","o'zaro ta'sir"],["간판","peshlavha, reklama taxtasi"],["헤매다","sarson bo'lmoq"],["조기 교육","erta yoshda ta'lim"],
    ["발음","talaffuz"],["찬반양론","tarafdor va qarshi fikrlar"],["팽팽하다","teng kuchli, tarang"],["희박하다","susaymoq, siyraklashmoq"],["불 보듯 뻔하다","ko'z oldida ravshan"],["미생물","mikroorganizm"],
    ["배양하다","o'stirmoq, ko'paytirmoq"],["멸종","qirilib ketish"],["방치하다","e'tiborsiz qoldirmoq"],["고갈","tugab qolish"],["노폐물","chiqindi modda"],["축적","to'planish"],
    ["괘씸하다","g'azablantiruvchi"],["섭섭하다","ranjimoq, xafa bo'lmoq"],["안쓰럽다","rahmi kelmoq"],["간절하다","chin dildan, o'tinib"],["중얼거리다","ming'irlamoq"],["코끝이 찡하다","ta'sirlanib ko'zi yoshlanmoq"],
    ["화제","muhokama mavzusi"],["홍보","reklama, targ'ibot"],["휴양림","dam olish o'rmoni"],["성수기","mavsum avji"],["비수기","past mavsum"],["연봉","yillik maosh"],
    ["채용하다","ishga olmoq"],["몸짓","imo-ishora"],["팔꿈치","tirsak"],["개방적","ochiq, xolis"],["포용력","bag'rikenglik"],["무례하다","beadab, qo'pol"],
    ["부정행위","aldov, ko'chirish"],["감독","nazorat, kuzatuv"],["도입하다","joriy qilmoq"],["명예","sha'n, obro'"],["유혹","vasvasa"],["뿌리치다","rad etmoq, silkib tashlamoq"],
    ["가령","masalan, aytaylik"],["벼락","chaqmoq, yashin"],["시달리다","azob chekmoq"],["뉘우치다","tavba qilmoq"],["형벌","jazo"],["분량","hajm, miqdor"],
    ["편집(하다)","montaj, tahrirlash"],["생동감","jonlilik"],["연출하다","sahnalashtirmoq"],["비로소","shundagina"],["기한","muddat"],["유통","muomala, tarqatish"],
    ["표기하다","belgilab yozmoq"],["혼동하다","chalkashtirmoq"],["추위","sovuq"],["체온","tana harorati"],["조절(하다)","sozlash, moslash"],["관여하다","aloqador bo'lmoq"],
    ["항암","saratonga qarshi"],["함유하다","o'z ichiga olmoq"],["섬유질","tola, kletchatka"],["효능","shifobaxsh xususiyat"],["데치다","qaynoq suvda pishirmoq"],["호소하다","shikoyat qilmoq"],
    ["잔업","qo'shimcha ish"],["허다하다","juda ko'p uchraydi"],["땅콩","yer yong'og'i"],["주전부리","yengil gazak"],["배출하다","tashqariga chiqarmoq"],["반려견","uy iti"],
    ["착용하다","kiymoq, taqmoq"],["목줄","bo'yin bog'ich"],["장단점","yaxshi va yomon tomon"],["소모하다","sarflamoq"],["창업","biznes boshlash"],["시행착오","sinov va xato"],
    ["전수받다","tajribasini qabul qilmoq"],["실전","amaliy tajriba"],["타자","urib o'ynovchi"],["투수","to'p uloqtiruvchi"],["전향하다","yo'nalishini o'zgartirmoq"],["영리하다","zukko, aqlli"],
    ["쌍둥이","egizak"],["수정란","urug'langan tuxum"],["세포","hujayra"],["유전자","gen"],["동일하다","bir xil, aynan"],["난자","tuxum hujayra"],
    ["안도하다","xotirjam bo'lmoq"],["원망하다","gina qilmoq"],["안부","hol-ahvol xabari"],["가슴을 태우다","ich-ichidan kuymoq"],["생사","hayot va o'lim"],["운명","taqdir"],
    ["주저앉다","cho'kkalab qolmoq"],["규명","aniqlab olish"],["재발","qaytalanish"],["방지(하다)","oldini olish"],["우왕좌왕하다","sarosimaga tushmoq"],["불감증","sezgirlik yo'qligi"],
    ["부주의","e'tiborsizlik"],["규제","cheklov, tartibga solish"],["실효성","amaliy samara"],["숙취","ichkilikdan keyingi holat"],["독성","zaharlilik"],["쓰리다","achishmoq"],
    ["주성분","asosiy tarkibiy qism"],["흡수되다","so'rilmoq"],["분해하다","parchalamoq"],["필자","muallif"],["인턴제","internatura tizimi"],["인증(하다)","sertifikatlash, tasdiqlash"],
    ["촉구하다","chaqirmoq, talab qilmoq"],["실습","amaliy mashg'ulot"],["직무","lavozim vazifasi"],["체험","tajriba, sinab ko'rish"],["회의적","shubha bilan, skeptik"],["산재되다","tarqalib yotmoq"]
  ] });
