MASTER_WORDS({ id:"tmw-읽기-3", type:"read", label:"TOPIK MASTER 제3회 읽기 so'zlari",
  title:"제3회 읽기", sub:"TOPIK MASTER · 읽기 so'zlari",
  words:[
    ["생산량","ishlab chiqarish hajmi"],["대체적으로","umuman, asosan"],["조절(하다)","nazorat qilish, moslashtirish"],["꽂다","qadamoq, tiqmoq"],["나아지다","yaxshilanmoq"],["안타깝다","achinarli"],
    ["-에도 불구하고","qaramay"],["상큼하다","yoqimli, tetiklantiruvchi"],["비결","sir, usul"],["쾌적하다","qulay, shinam"],["주거","turar joy"],["절약(하다)","tejash"],
    ["물려주다","meros qilib bermoq"],["화상을 입다","kuyib qolmoq"],["민간요법","xalq tabobati"],["응급 처치","birinchi yordam"],["수화","imo-ishora tili"],["상담(하다)","maslahat berish"],
    ["개통","ishga tushirish"],["청각 장애인","eshitish nuqsonli kishi"],["현황","hozirgi holat"],["석탄","ko'mir"],["원자력","atom energiyasi"],["격차","tafovut, farq"],
    ["차지하다","egallamoq"],["신용 불량자","qarzini to'lamagan kishi"],["전락하다","tushib qolmoq"],["통계","statistika"],["갚다","qarzni to'lamoq"],["연령대","yosh guruhi"],
    ["전자책","elektron kitob"],["구독","obuna"],["대체하다","o'rnini bosmoq"],["추세","tendensiya"],["대여","ijaraga berish"],["등한시하다","e'tiborsiz qoldirmoq"],
    ["어업","baliqchilik"],["중요시하다","muhim deb bilmoq"],["탐구","izlanish, tadqiqot"],["과다","haddan ziyod"],["섭취(하다)","iste'mol qilish"],["탄수화물","uglevod"],
    ["권고하다","tavsiya qilmoq"],["분야","soha"],["까다롭다","injiq, talabchan"],["전략","strategiya"],["퇴고","matnni tahrirlash"],["다듬다","silliqlamoq, saralamoq"],
    ["소재","mavzu ashyosi"],["맞춤법","imlo"],["연예인","mashhur artist"],["눈에 띄다","ko'zga tashlanmoq"],["분양","sotuvga chiqarish"],["친근감","yaqinlik hissi"],
    ["건조시키다","quritmoq"],["제작하다","yasamoq, tayyorlamoq"],["정성","mehr, jon kuydirish"],["명품","nodir brend mahsulot"],["아예","butunlay, umuman"],["고작","bor-yo'g'i"],
    ["양서류","suvda-quruqlikda yashovchilar"],["파충류","sudralib yuruvchilar"],["벼는 익을수록 고개를 숙인다","bilimli kishi kamtar bo'ladi"],["겸손하다","kamtar bo'lmoq"],["교만","manmanlik, takabburlik"],["능숙하다","mohir, tajribali"],
    ["초보자","yangi boshlovchi"],["-기 마련이다","albatta shunday bo'ladi"],["담담하다","xotirjam, sovuqqon"],["억울하다","nohaqlikdan ranjigan"],["그림자놀이","soya o'yini"],["멀어지다","uzoqlashmoq"],
    ["추억","xotira, esdalik"],["담뱃값","sigaret narxi"],["인상","narx oshirish"],["금연","chekishni tashlash"],["사고방식","fikrlash tarzi"],["선호하다","afzal ko'rmoq"],
    ["중년층","o'rta yoshlilar"],["호감","iliq munosabat"],["입상작","sovrinli asar"],["거세다","shiddatli, kuchli"],["소득","daromad"],["망각하다","unutmoq"],
    ["몰두하다","berilib ketmoq"],["집착하다","yopishib olmoq"],["파산","bankrotlik"],["존경","hurmat"],["관습","urf-odat"],["용도","qo'llanilishi, vazifasi"],
    ["환영","kutib olish"],["지배 계층","hukmron tabaqa"],["풍자하다","hajv qilmoq"],["악인","yovuz odam"],["증오하다","nafratlanmoq"],["이민자","muhojir"],
    ["강대국","buyuk davlat"],["종속되다","qaram bo'lmoq"],["민중","oddiy xalq"],["극복하다","yengib o'tmoq"],["효소","ferment"],["면역","immunitet"],
    ["유발하다","keltirib chiqarmoq"],["유전자","gen"],["번식력","ko'payish qobiliyati"],["구인난","ishchi topish tanqisligi"],["애를 먹다","qiynalmoq"],["요인","omil"],
    ["인력","ishchi kuchi"],["본성","tabiat, fitrat"],["분쟁","nizo, to'qnashuv"],["경쟁심","raqobat hissi"],["존엄성","qadr-qimmat"],["육아 휴직","bola parvarishi ta'tili"],
    ["경력 단절","mehnat yo'lining uzilishi"],["단축","qisqartirish"],["생산성","unumdorlik"],["개정","qayta ko'rib chiqish"],["사고력","fikrlash qobiliyati"],["교구","o'quv qo'llanmasi"],
    ["개념","tushuncha"],["난민","qochqin"],["참혹하다","dahshatli, fojiali"],["수용","qabul qilish"],["외면하다","yuz o'girmoq"],["혈압","qon bosimi"],
    ["약효","dorining ta'siri"],["부작용","nojo'ya ta'sir"],["버섯","qo'ziqorin"],["식욕","ishtaha"],["예방하다","oldini olmoq"],["효능","foydali xususiyat"],
    ["실의에 빠지다","umidsizlikka tushmoq"],["엄격하다","qattiqqo'l, qat'iy"],["자본주의","kapitalizm"],["추구하다","intilmoq, ko'zlamoq"],["탈락하다","saf tashqarisiga chiqmoq"],["치열하다","qizg'in, keskin"],
    ["추수","hosil yig'imi"],["가꾸다","parvarish qilmoq"],["흉작","hosilsizlik"],["빚","qarz"],["부끄럽다","uyalmoq"],["의심을 받다","gumon ostida qolmoq"],
    ["신경","nerv"],["퇴화하다","susaymoq, orqaga ketmoq"],["분비","ajralib chiqish"],["감소하다","kamaymoq"],["증상","alomat, simptom"],["간호사","hamshira"],
    ["편견","noto'g'ri qarash"],["직종","kasb turi"],["대두되다","kun tartibiga chiqmoq"],["뒷받침하다","asoslab bermoq"],["필자","muallif"],["임신","homiladorlik"],
    ["출산","tug'ish"],["공무원","davlat xizmatchisi"],["배려하다","e'tibor ko'rsatmoq"],["면제되다","ozod qilinmoq"]
  ] });
